### ISSUE TITLE
Usage to playback video-audio live streaming on browser

### ISSUE THREAD

**Issue by ghost** [joelam789/sharp-broadcast#1]
Hi,

It's really cool live streaming project. I'd like to integrate that with my project. 

So, First of all, I'd would to know the usage.

I build the solution, started up the **Media Encoder** and the **Media Server**. All them start up ok, but I couldn't playback on browser using **main.html** or **mpeg.html**

**Comment by joelam789** [comment]
Sorry for my late reply!
Can you give the screenshots about your running **Media Server** and **Media Encoder**?

**Comment by ghost** [comment]
Don't worry about it. Yes, I can.

Encoder
![encoder](https://user-images.githubusercontent.com/21323185/29874218-7a52f424-8d6c-11e7-9551-34d6566ecbf7.png)

Server
![server](https://user-images.githubusercontent.com/21323185/29874242-898024bc-8d6c-11e7-870e-ed7d156b0366.png)

Running main.html
![running1](https://user-images.githubusercontent.com/21323185/29874275-a2a934c4-8d6c-11e7-95ca-ce5089cfcca3.png)

![running2](https://user-images.githubusercontent.com/21323185/29874289-a8b8684e-8d6c-11e7-9a97-b41868f5e037.png)

![running3](https://user-images.githubusercontent.com/21323185/29874296-aef417ee-8d6c-11e7-8abd-a501588e25e2.png)

**Comment by joelam789** [comment]
No need to modify **main.html**
You may undo your changes (revert it from git) to solve the problem.

Your Media Server is listening on port 9320, which is for stream players to connect.
You may find the information about the ports from Media Server's log.
If you want  to change the ports, you may modify **App.config**

Media Server's "Input" ports are for encoders to connect.
Media Server's "Output" ports are for stream players to connect.

**Comment by ghost** [comment]
I reverted the changes.

It is no working on Chrome  60.0.3112.113. Only in Firefox.

I'm getting a huge delay. As an example, using Camera a Microphone device. The delay is about 10 seconds.

So how can I get a subseconds?

**Comment by joelam789** [comment]
Please put **main.html** to a Web Server (e.g. IIS, Apache, Nginx, etc)
and open it with Chrome via a URL starting with "http://" (not "file://"),  then you will see the video.

About the delay, i think it might be related to your hardware spec.
So the help i can provide here is very limited... sorry.

In my test, i can achieve sub-second delay on Windows 7/10 with
**intel i5-2320 cpu + logitech hd pro webcam c910**

Maybe you can try to run it on another faster computer.
Good luck.
