### ISSUE TITLE
Testing mobile browser on Android

### ISSUE THREAD

**Issue by ghost** [joelam789/sharp-broadcast#3]
Hi again,

I was trying to do some test using **main.html** in the mobile browsers on **Android** . So I tested with the latest **Chrome, Firefox and Opera** (with Websocket support) version but unfortunally anyone could connect to the **Media Server**.  All the desktop browser worked very well. 

So is there any special parameters missing?

Best regards,
Daniel

**Comment by joelam789** [comment]
You need to change the IP address of **Media Server** in the original **main.html**.

https://github.com/joelam789/sharp-broadcast/blob/master/LiveStreamingClient/main.html#L27
``` javascript
var mediaServerIp = "127.0.0.1";
```

Change "127.0.0.1" to another IP (but still one of the IP addresses of **Media Server**)
that your mobile is able to access.

**Comment by ghost** [comment]
Thanks man

The only IP that it worked was my **localhost ip**

`var mediaServerIp = "192.168..0.3"; //localhost`

Doing some test with **Chrome, Firefox and Opera mobile** on Android I perceive that **Firefox** deal better with **JavaScript Broadway decoder** achieving perfomance closer to the **Desktop** =)
