### ISSUE TITLE
Jsmepg is not connecting to the Media Server

### ISSUE THREAD

**Issue by ghost** [joelam789/sharp-broadcast#4]
Another issue. 

**mpeg.html** is not connect to the **Media Server**. Using the same **IP** and **port** and the channelName **test-mpeg**

	var url = 'ws://127.0.0.1:9420/test-mpeg'; 

So do you have any tips about that?

**Comment by joelam789** [comment]
You need to create a new channel for the mpeg test.

For example:

![image](https://user-images.githubusercontent.com/13307068/30949326-4731807c-a448-11e7-9527-c5dbe5916cf2.png)

**Comment by ghost** [comment]
Great man!  =)

It's  working now
