### ISSUE TITLE
Stream my microfone in an audio channel using mp2 support by the Jsmpeg

### ISSUE THREAD

**Issue by ghost** [joelam789/sharp-broadcast#5]
How can i stream my microfone in an audio channel using **mp2** support by the **Jsmpeg** ?

In this case below, I can encode the **video** and the **audio** in same **Media-Server-IP+Video-Channel+Type+specs** to use with **Jsmpeg** and it work:

`ffmpeg -re -i "rtmp://live.hkstv.hk.lxdns.com/live/hks" -s 800x600 -r 30 -b:v 800k -an -codec:v mpeg1video -bf 0 -codec:a mp2 -b:a 128k  -pix_fmt yuv420p -g 60 -threads 1 -f mpegts http://127.0.0.1:9410/test-mpeg/mpeg/800x600x30@800kbps` 

But in the **Webcam+microfone** case when I put my microfone in separeted **audio channel**  it not work:

`ffmpeg -frame_drop_threshold 4 -f dshow -rtbufsize 1024M -i video="WebCam SC-13HDL12131N" -s 640x480 -r 30 -b:v 640k -an -codec:v mpeg1video -bf 0 -f mpegts http://127.0.0.1:9410/test-mpeg/mpeg/640x480x30@640kbps -f dshow -audio_buffer_size 100 -i audio="Microfone (Realtek High Definition Audio)" -vn -codec:a mp2 -b:a 128k -f mp2 http://127.0.0.1:9210/desktop-48000/mp2/48000` 

So in this last case how can i merge the **video+audio** ?

**Comment by joelam789** [comment]
oh... that should be a defect of the encoder.
i fixed it just now, please get the latest version from git and try again.

Example:

![image](https://user-images.githubusercontent.com/13307068/30998421-f094e772-a500-11e7-90b9-021ae6709d52.png)

Command line:
``` bat
ffmpeg -f dshow -rtbufsize 1024M -i video="screen-capture-recorder" -f dshow -audio_buffer_size 100 -i audio="virtual-audio-capturer"  -s 640x360 -r 20 -b:v 512k  -codec:v mpeg1video -bf 0  -f mpegts http://127.0.0.1:9410/test-mpeg/mpeg/640x360x20@512kbps
```
